/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TProtocolFactory.h"
#import "TApplicationError.h"
#import "TProtocolError.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TBase.h"
#import "TAsyncTransport.h"
#import "TBaseClient.h"


@interface PrivateAnswer : NSObject <TBase, NSCoding, NSCopying> 

@property (assign, nonatomic) SInt64 analystId;
@property (assign, nonatomic) BOOL analystIdIsSet;
- (void) unsetAnalystId;

@property (assign, nonatomic) SInt64 queryId;
@property (assign, nonatomic) BOOL queryIdIsSet;
- (void) unsetQueryId;

@property (strong, nonatomic) NSData * privateAnswerBits;
@property (assign, nonatomic) BOOL privateAnswerBitsIsSet;
- (void) unsetPrivateAnswerBits;

@property (assign, nonatomic) SInt32 bitlen;
@property (assign, nonatomic) BOOL bitlenIsSet;
- (void) unsetBitlen;

@property (assign, nonatomic) SInt64 joinId;
@property (assign, nonatomic) BOOL joinIdIsSet;
- (void) unsetJoinId;

@property (assign, nonatomic) SInt64 versionId;
@property (assign, nonatomic) BOOL versionIdIsSet;
- (void) unsetVersionId;


- (instancetype) initWithAnalystId: (SInt64) analystId queryId: (SInt64) queryId privateAnswerBits: (NSData *) privateAnswerBits bitlen: (SInt32) bitlen joinId: (SInt64) joinId versionId: (SInt64) versionId;

@end

FOUNDATION_EXPORT NSString *PrivateAnswerErrorDomain;


