/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TProtocolFactory.h"
#import "TApplicationError.h"
#import "TProtocolError.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TBase.h"
#import "TAsyncTransport.h"
#import "TBaseClient.h"


typedef NS_ENUM(SInt32, SensorType) {
  SensorTypeLOCATION = 0,
  SensorTypeGYROSCOPE = 1,
  SensorTypeACCELEROMETER = 2,
  SensorTypeMAGNETOMETER = 3,
  SensorTypePROXIMITY = 4,
  SensorTypeBRIGHTNESS = 5,
  SensorTypeSOUNDLEVEL = 6,
  SensorTypeBATTERYLEVEL = 7,
  SensorTypeWIFIDATAUSAGE = 8,
  SensorTypeCELLDATAUSAGE = 9
};

typedef NS_ENUM(SInt32, MatchingType) {
  MatchingTypeLOCATION_MATCHING = 0,
  MatchingTypeNUMERICAL_MATCHING = 1,
  MatchingTypeSTRING_MATCHING = 2
};

@interface QueryVector : NSObject <TBase, NSCoding, NSCopying> 

@property (strong, nonatomic) NSMutableArray<NSString *> * ranges;
@property (assign, nonatomic) BOOL rangesIsSet;
- (void) unsetRanges;


- (instancetype) initWithRanges: (NSArray<NSString *> *) ranges;

@end

@interface Query : NSObject <TBase, NSCoding, NSCopying> 

@property (assign, nonatomic) SInt64 analystId;
@property (assign, nonatomic) BOOL analystIdIsSet;
- (void) unsetAnalystId;

@property (assign, nonatomic) SInt64 queryId;
@property (assign, nonatomic) BOOL queryIdIsSet;
- (void) unsetQueryId;

@property (assign, nonatomic) SInt64 queryStartTime;
@property (assign, nonatomic) BOOL queryStartTimeIsSet;
- (void) unsetQueryStartTime;

@property (assign, nonatomic) SInt64 queryEndTime;
@property (assign, nonatomic) BOOL queryEndTimeIsSet;
- (void) unsetQueryEndTime;

@property (assign, nonatomic) SInt64 epoch;
@property (assign, nonatomic) BOOL epochIsSet;
- (void) unsetEpoch;

@property (assign, nonatomic) SensorType sensorType;
@property (assign, nonatomic) BOOL sensorTypeIsSet;
- (void) unsetSensorType;

@property (assign, nonatomic) MatchingType matchingType;
@property (assign, nonatomic) BOOL matchingTypeIsSet;
- (void) unsetMatchingType;

@property (strong, nonatomic) QueryVector * queryVector;
@property (assign, nonatomic) BOOL queryVectorIsSet;
- (void) unsetQueryVector;

@property (assign, nonatomic) double epsilon;
@property (assign, nonatomic) BOOL epsilonIsSet;
- (void) unsetEpsilon;

@property (strong, nonatomic) NSString * flipOne;
@property (assign, nonatomic) BOOL flipOneIsSet;
- (void) unsetFlipOne;

@property (strong, nonatomic) NSString * flipTwo;
@property (assign, nonatomic) BOOL flipTwoIsSet;
- (void) unsetFlipTwo;

@property (assign, nonatomic) SInt64 versionId;
@property (assign, nonatomic) BOOL versionIdIsSet;
- (void) unsetVersionId;


- (instancetype) initWithAnalystId: (SInt64) analystId queryId: (SInt64) queryId queryStartTime: (SInt64) queryStartTime queryEndTime: (SInt64) queryEndTime epoch: (SInt64) epoch sensorType: (SensorType) sensorType matchingType: (MatchingType) matchingType queryVector: (QueryVector *) queryVector epsilon: (double) epsilon flipOne: (NSString *) flipOne flipTwo: (NSString *) flipTwo versionId: (SInt64) versionId;

@end

FOUNDATION_EXPORT NSString *QueryErrorDomain;


