/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"
#import "TAsyncTransport.h"
#import "TProtocolFactory.h"
#import "TBaseClient.h"


enum SensorType {
  SensorType_LOCATION = 0,
  SensorType_GYROSCOPE = 1,
  SensorType_ACCELEROMETER = 2,
  SensorType_MAGNETOMETER = 3,
  SensorType_PROXIMITY = 4,
  SensorType_BRIGHTNESS = 5,
  SensorType_SOUNDLEVEL = 6
};

enum MatchingType {
  MatchingType_LOCATION_MATCHING = 0,
  MatchingType_NUMERICAL_MATCHING = 1,
  MatchingType_STRING_MATCHING = 2
};

@interface QueryVector : NSObject <TBase, NSCoding> {
  int __matchingtype;
  int __querytype;
  NSMutableArray * __ranges;

  BOOL __matchingtype_isset;
  BOOL __querytype_isset;
  BOOL __ranges_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=matchingtype, setter=setMatchingtype:) int matchingtype;
@property (nonatomic, getter=querytype, setter=setQuerytype:) int querytype;
@property (nonatomic, retain, getter=ranges, setter=setRanges:) NSMutableArray * ranges;
#endif

- (id) init;
- (id) initWithMatchingtype: (int) matchingtype querytype: (int) querytype ranges: (NSMutableArray *) ranges;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int) matchingtype;
- (void) setMatchingtype: (int) matchingtype;
#endif
- (BOOL) matchingtypeIsSet;

#if !__has_feature(objc_arc)
- (int) querytype;
- (void) setQuerytype: (int) querytype;
#endif
- (BOOL) querytypeIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) ranges;
- (void) setRanges: (NSMutableArray *) ranges;
#endif
- (BOOL) rangesIsSet;

@end

@interface Query : NSObject <TBase, NSCoding> {
  int64_t __analystId;
  int64_t __queryId;
  int64_t __queryStartTime;
  int64_t __queryEndTime;
  int64_t __epoch;
  int __queryType;
  double __epsilon;
  QueryVector * __queryVector;
  NSString * __p;
  NSString * __q;
  int64_t __versionId;

  BOOL __analystId_isset;
  BOOL __queryId_isset;
  BOOL __queryStartTime_isset;
  BOOL __queryEndTime_isset;
  BOOL __epoch_isset;
  BOOL __queryType_isset;
  BOOL __epsilon_isset;
  BOOL __queryVector_isset;
  BOOL __p_isset;
  BOOL __q_isset;
  BOOL __versionId_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=analystId, setter=setAnalystId:) int64_t analystId;
@property (nonatomic, getter=queryId, setter=setQueryId:) int64_t queryId;
@property (nonatomic, getter=queryStartTime, setter=setQueryStartTime:) int64_t queryStartTime;
@property (nonatomic, getter=queryEndTime, setter=setQueryEndTime:) int64_t queryEndTime;
@property (nonatomic, getter=epoch, setter=setEpoch:) int64_t epoch;
@property (nonatomic, getter=queryType, setter=setQueryType:) int queryType;
@property (nonatomic, getter=epsilon, setter=setEpsilon:) double epsilon;
@property (nonatomic, retain, getter=queryVector, setter=setQueryVector:) QueryVector * queryVector;
@property (nonatomic, retain, getter=p, setter=setP:) NSString * p;
@property (nonatomic, retain, getter=q, setter=setQ:) NSString * q;
@property (nonatomic, getter=versionId, setter=setVersionId:) int64_t versionId;
#endif

- (id) init;
- (id) initWithAnalystId: (int64_t) analystId queryId: (int64_t) queryId queryStartTime: (int64_t) queryStartTime queryEndTime: (int64_t) queryEndTime epoch: (int64_t) epoch queryType: (int) queryType epsilon: (double) epsilon queryVector: (QueryVector *) queryVector p: (NSString *) p q: (NSString *) q versionId: (int64_t) versionId;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) analystId;
- (void) setAnalystId: (int64_t) analystId;
#endif
- (BOOL) analystIdIsSet;

#if !__has_feature(objc_arc)
- (int64_t) queryId;
- (void) setQueryId: (int64_t) queryId;
#endif
- (BOOL) queryIdIsSet;

#if !__has_feature(objc_arc)
- (int64_t) queryStartTime;
- (void) setQueryStartTime: (int64_t) queryStartTime;
#endif
- (BOOL) queryStartTimeIsSet;

#if !__has_feature(objc_arc)
- (int64_t) queryEndTime;
- (void) setQueryEndTime: (int64_t) queryEndTime;
#endif
- (BOOL) queryEndTimeIsSet;

#if !__has_feature(objc_arc)
- (int64_t) epoch;
- (void) setEpoch: (int64_t) epoch;
#endif
- (BOOL) epochIsSet;

#if !__has_feature(objc_arc)
- (int) queryType;
- (void) setQueryType: (int) queryType;
#endif
- (BOOL) queryTypeIsSet;

#if !__has_feature(objc_arc)
- (double) epsilon;
- (void) setEpsilon: (double) epsilon;
#endif
- (BOOL) epsilonIsSet;

#if !__has_feature(objc_arc)
- (QueryVector *) queryVector;
- (void) setQueryVector: (QueryVector *) queryVector;
#endif
- (BOOL) queryVectorIsSet;

#if !__has_feature(objc_arc)
- (NSString *) p;
- (void) setP: (NSString *) p;
#endif
- (BOOL) pIsSet;

#if !__has_feature(objc_arc)
- (NSString *) q;
- (void) setQ: (NSString *) q;
#endif
- (BOOL) qIsSet;

#if !__has_feature(objc_arc)
- (int64_t) versionId;
- (void) setVersionId: (int64_t) versionId;
#endif
- (BOOL) versionIdIsSet;

@end

@interface QueryConstants : NSObject {
}
@end
