/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.dataluminosity.privacy.message;


public enum MatchingType implements org.apache.thrift.TEnum {
  LOCATION_MATCHING(0),
  NUMERICAL_MATCHING(1),
  STRING_MATCHING(2);

  private final int value;

  private MatchingType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static MatchingType findByValue(int value) { 
    switch (value) {
      case 0:
        return LOCATION_MATCHING;
      case 1:
        return NUMERICAL_MATCHING;
      case 2:
        return STRING_MATCHING;
      default:
        return null;
    }
  }
}
