/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.dataluminosity.privacy.message;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum SensorType implements org.apache.thrift.TEnum {
  LOCATION(0),
  GYROSCOPE(1),
  ACCELEROMETER(2),
  MAGNETOMETER(3),
  PROXIMITY(4),
  BRIGHTNESS(5),
  SOUNDLEVEL(6);

  private final int value;

  private SensorType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static SensorType findByValue(int value) { 
    switch (value) {
      case 0:
        return LOCATION;
      case 1:
        return GYROSCOPE;
      case 2:
        return ACCELEROMETER;
      case 3:
        return MAGNETOMETER;
      case 4:
        return PROXIMITY;
      case 5:
        return BRIGHTNESS;
      case 6:
        return SOUNDLEVEL;
      default:
        return null;
    }
  }
}
